# 2DOF Beam

The general mathematical representation of a single degree of freedom system is expressed using Newton's second law. It is a linear, time invariant, second order differential equation.

\begin{equation}
M \ddot{x} \left ( t \right ) + C \dot{x}\left (t \right ) + K x \left (t \right ) = f \left (t \right )
\end{equation}



## Setup



In [29]:
import numpy as np
from scipy import linalg as la

show = lambda x,y: print('{}:\n{}\n'.format(x,y))

## Build Beam



In [57]:
b = 1              # in
h = 12             # in
I = b*(h**3)/12       # in^4
E = 29e6           # psi 
l = 100*12         # ft -> in
grav = 386.4       # in/sec^2;
mbar = b*h*.29     # vol * density -> lbf
mbar = mbar/grav   # lbm

# define discrete boundary springs
k1 = E*I/(l**3) * 300
k2 = E*I/l**3 * 300

# form mass matrix, [M]
M = mbar*l/2 * np.eye(2)

# form stiffness matrix, [K] from beam and springs
k = E*I/(l**3)  * np.array([[12, -12 ] , [-12, 12]])
K = k + np.eye(2)*np.array([k1,k2]) 


show('Mass matrix',M)
show('Stiffness matrix',K)

# TODO: Add beam plot

Mass matrix:
[[ 5.40372671  0.        ]
 [ 0.          5.40372671]]

Stiffness matrix:
[[ 754.  -29.]
 [ -29.  754.]]



## Eigenvalue Decomposition



Modal vectors and system poles (damped natural frequencies).

Proportionally damped system - modal vectors are always real (normal) modes. Therefore, the conjugate of a modal vector is the same as the modal vector.


In [56]:
# decomposition (use hermetian for square matrices) 
d, v = la.eigh(K,M)

# damped natural frequencies [rad/sec]
w = np.sqrt(d)

# decoupled mass and stiffness matrices
# note that the two matrix multiplication's below are equivalent. 
Mr = np.dot(np.dot(v.T,M), v) # works but ugly
Kr = v.T@K@v                  # works but only in python3.5+


# proportional damping [5% critical]
dampr = .05

# damping factor [rad/sec]
dampf = -dampr*w

# damped natural frequency [rad/sec]
wn = np.sqrt(w**2 + dampf**2)

# form positive poles
roots = dampf + 1j*wn


show('Eigenvalues',d)
show('Eigenvectors',v)
show('Decoupled Mass Matrix', Mr)
show('Decoupled Stiffness Matrix',Kr)

Eigenvalues:
[ 134.16666667  144.9       ]

Eigenvectors:
[[-0.30418536 -0.30418536]
 [-0.30418536  0.30418536]]

Decoupled Mass Matrix:
[[ 1.  0.]
 [ 0.  1.]]

Decoupled Stiffness Matrix:
[[ 134.16666667    0.        ]
 [   0.          144.9       ]]



TODO: add shape plots

In [ ]:
# plot mode shapes

## Transfer Function

Form transfer function from partial fraction expansion form


In [54]:

# modal scaling, Qr
qr = 1/(2j*-roots)

# scaled residues [Ar] for each mode
A = [qr[mode]*np.outer(v[:,mode],v[:,mode]) for mode in np.arange(v.shape[1])]

# evaluate along frequency domain



### Frequency Response Function (FRF) Plots



## Shape Estimation (CMIF via SVD)



## Pole Estimation (eFRF)



## Modal Flexibility