# Misc Python Examples and Benchmarks



## Numpy



In [4]:
import numpy as np


a = np.arange(30).reshape(2,3,5) 
print(a)


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [12]:
print(a[0])


print(a.strides)
print(a.ndim)
print(a.flags)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(60, 20, 4)
3
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
